class AppStrings {
  static const Map<String, Map<String, String>> localizedValues = {
    'en': {
      // Branding & Splash
      'brandName': 'Valuate',
      'brandSubtitle': 'Real Estate Intelligence',
      'brandTagline': "The MENA region's first automated feasibility study platform for real-estate.",
      'brandDescription': 'Model construction costs, revenue phasing, and investment returns in minutes — built on live regional market data, not assumptions.',
      'copyright': '© 2026 Gateway Financials',

      // Auth - Common
      'signIn': 'Sign in',
      'signUp': 'Sign Up',
      'welcomeBack': 'Welcome back',
      'getStarted': 'Get started',
      'createAccount': 'Create your account',
      'freeTrialNote': 'Start your free trial. No credit card required.',
      'signInLead': 'Access your account by entering your registered email and password.',
      'emailLabel': 'Company email',
      'emailPlaceholder': 'Enter company email',
      'passwordLabel': 'Password',
      'passwordPlaceholder': 'Enter password',
      'firstNameLabel': 'First name',
      'firstNamePlaceholder': 'First name',
      'lastNameLabel': 'Last name',
      'lastNamePlaceholder': 'Last name',
      'companyLabel': 'Company name',
      'companyPlaceholder': 'Your company',
      'phoneLabel': 'Phone number',
      'phonePlaceholder': '+966 5X XXX XXXX',
      'createPasswordPlaceholder': 'Create a strong password',
      'keepLoggedIn': 'Keep me logged in',
      'forgotPassword': 'Forgot your password?',
      'dontHaveAccount': "Doesn't have an account?",
      'alreadyHaveAccount': 'Already have an account?',
      'termsNotice': 'By clicking "Create account", you agree to our Terms of Service and Privacy Policy.',
      'termsOfService': 'Terms of Service',
      'privacyPolicy': 'Privacy Policy',
      'resetPassword': 'Reset password',
      'resetPasswordLead': 'Enter your email to receive a password reset link.',
      'sendResetLink': 'Send reset link',
      'backToLogin': 'Back to Sign In',
      'continueAsGuest': 'Continue as Guest',
      'exploreAsGuest': 'Explore as Guest',
      'guestSubtitle': 'Access feasibility models & market benchmarks without an account',
      'guestUser': 'Guest User',
      'guestMode': 'Explore Mode (Guest)',
      'guestNotice': 'You are currently exploring as a guest.',
      'guestBannerTitle': 'Browsing as Guest',
      'guestBannerDesc': 'Sign in or create a free account to save your profile and sync studies across devices.',
      'signInOrRegister': 'Sign In / Register',
      'accountRequired': 'Account Required',
      'accountRequiredMessage': 'This feature requires a free account. Would you like to sign in or create an account now?',
      'exitGuestMode': 'Exit Guest Mode',
      'orDivider': 'OR',

      // Navigation
      'navDashboard': 'Dashboard',
      'navProjects': 'Projects',
      'navMarket': 'Intelligence',
      'navSettings': 'Settings',

      // Dashboard
      'portfolioOverview': 'Portfolio Feasibility Overview',
      'activeProjects': 'Active Studies',
      'totalPipelineValue': 'Total Pipeline',
      'averageRoi': 'Average ROI',
      'marketTrend': 'MENA Benchmark',
      'recentStudies': 'Recent Feasibility Studies',
      'viewAll': 'View all',
      'newStudy': '+ New Study',
      'goDecision': 'GO',
      'noGoDecision': 'NO-GO',
      'cautionDecision': 'CAUTION',
      'liveMarketUpdate': 'Live Regional Intelligence',

      // Feasibility & Financial Metrics
      'projectDetails': 'Project Definition',
      'projectName': 'Project Name',
      'projectType': 'Asset Type',
      'location': 'Location / Market',
      'landArea': 'Plot / Land Area',
      'far': 'FAR (Floor Area Ratio)',
      'bua': 'Built-up Area (BUA)',
      'gfa': 'Gross Floor Area (GFA)',
      'landCost': 'Land Acquisition Cost',
      'constructionCostPerSqm': 'Construction Cost / m²',
      'softCostPct': 'Soft Costs (%)',
      'contingencyPct': 'Contingency (%)',
      'expectedRevenuePerSqm': 'Expected Sale / Revenue per m²',
      'developmentPeriodMonths': 'Development Duration (Months)',
      'calculate': 'Run Feasibility Model',
      'verdict': 'Feasibility Verdict',
      'verdictScore': 'Feasibility Score',
      'totalDevelopmentCost': 'Total Development Cost (TDC)',
      'grossRevenue': 'Gross Projected Revenue',
      'netProfit': 'Net Profit (EBIT)',
      'roi': 'Return on Investment (ROI)',
      'irr': 'Project IRR (Annualized)',
      'equityMultiple': 'Equity Multiple (MOIC)',
      'profitMargin': 'Margin on Cost',
      'breakeven': 'Breakeven / m²',
      'costBreakdown': 'Cost Breakdown Analysis',
      'cashFlowProjection': 'Cash Flow & Phasing Timeline',
      'saveProject': 'Save to Projects',
      'exportPdf': 'Export Study Summary',
      'scenarioAnalysis': 'Scenario Sensitivity',
      'baseCase': 'Base Case',
      'bullCase': 'Bull Case (+10%)',
      'bearCase': 'Bear Case (-10%)',

      // Asset Types
      'residential': 'Residential',
      'commercial': 'Commercial / Office',
      'mixedUse': 'Mixed-Use',
      'hospitality': 'Hospitality',
      'retail': 'Retail',
      'industrial': 'Industrial / Logistics',

      // Markets
      'riyadh': 'Riyadh, Saudi Arabia',
      'jeddah': 'Jeddah, Saudi Arabia',
      'dubai': 'Dubai, UAE',
      'abuDhabi': 'Abu Dhabi, UAE',
      'cairo': 'Cairo, Egypt',
      'doha': 'Doha, Qatar',
      'kuwaitCity': 'Kuwait City, Kuwait',

      // Settings
      'profile': 'Profile & Organization',
      'appearance': 'Appearance',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'currency': 'Currency',
      'unit': 'Area Measurement Unit',
      'sqm': 'Square Meters (m²)',
      'sqft': 'Square Feet (sq ft)',
      'about': 'About Valuate',
      'version': 'Version 1.0.0 (MENA Cloud)',
      'signOut': 'Sign Out',
      'deleteAccount': 'Delete Account',

      // Project Wizard & Creation
      'createProjectTitle': 'Create Project',
      'createProjectSubtitleStep1': 'Basic project details, including name, location, and type to provide a comprehensive overview of project scope and objectives.',
      'createProjectSubtitleStep2': 'Financial modeling, construction parameters, and timeline for precise ROI & IRR calculations.',
      'step1Title': 'Standard Information',
      'step2Title': 'Financial Model',
      'developerName': 'Developer Name',
      'developerNamePlaceholder': 'Enter developer name',
      'projectNamePlaceholder': 'Enter project name',
      'projectSectors': 'Project Sectors',
      'strategyType': 'Type',
      'selectType': 'Select type',
      'selectCountry': 'Please select an option',
      'projectLocation': 'Project Location',
      'locationMapPlaceholder': 'Click to select location on map',
      'chooseOnMap': 'Choose on map',
      'landAreaSqm': 'Land Area',
      'country': 'Country',
      'citySubmarket': 'City / District',
      'landPaymentStructure': 'Land Payment Structure',
      'constructionSpecs': 'Construction & Floor Specs',
      'costAndPricing': 'Cost Benchmarks & Pricing',
      'developmentTimeline': 'Development Timeline',
      'previous': 'Previous',
      'next': 'Next',
      'saveAndCreate': 'Save & Create Project',

      // Alerts & Validation
      'fieldRequired': 'This field is required',
      'invalidEmail': 'Please enter a valid email address',
      'passwordLength': 'Password must be at least 6 characters',
      'studySavedSuccess': 'Project created and saved successfully in Valuate Workspace!',
      'linkSent': 'Reset instructions have been sent to your email.'
    },
    'ar': {
      // Branding & Splash
      'brandName': 'فاليوإيت',
      'brandSubtitle': 'ذكاء الاستثمار العقاري',
      'brandTagline': 'أول منصة مؤتمتة لدراسات الجدوى العقارية في منطقة الشرق الأوسط وشمال أفريقيا.',
      'brandDescription': 'نمذجة تكاليف البناء، ومراحل الإيرادات، وعوائد الاستثمار في دقائق — مبنية على بيانات السوق الإقليمية الحية، وليس التقديرات.',
      'copyright': '© 2026 جيتواي فاينانشالز',

      // Auth - Common
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'welcomeBack': 'مرحباً بعودتك',
      'getStarted': 'ابدأ الآن',
      'createAccount': 'أنشئ حسابك',
      'freeTrialNote': 'ابدأ تجربتك المجانية. لا يلزم وجود بطاقة ائتمان.',
      'signInLead': 'قم بالوصول إلى حسابك عن طريق إدخال بريدك الإلكتروني المسجل وكلمة المرور.',
      'emailLabel': 'البريد الإلكتروني للشركة',
      'emailPlaceholder': 'أدخل البريد الإلكتروني للشركة',
      'passwordLabel': 'كلمة المرور',
      'passwordPlaceholder': 'أدخل كلمة المرور',
      'firstNameLabel': 'الاسم الأول',
      'firstNamePlaceholder': 'الاسم الأول',
      'lastNameLabel': 'اسم العائلة',
      'lastNamePlaceholder': 'اسم العائلة',
      'companyLabel': 'اسم الشركة',
      'companyPlaceholder': 'شركتك العقارية',
      'phoneLabel': 'رقم الهاتف',
      'phonePlaceholder': '+966 5X XXX XXXX',
      'createPasswordPlaceholder': 'أنشئ كلمة مرور قوية',
      'keepLoggedIn': 'تذكر بيانات الدخول',
      'forgotPassword': 'هل نسيت كلمة المرور؟',
      'dontHaveAccount': 'ليس لديك حساب؟',
      'alreadyHaveAccount': 'هل لديك حساب بالفعل؟',
      'termsNotice': 'بالضغط على "إنشاء حساب"، فإنك توافق على شروط الخدمة وسياسة الخصوصية.',
      'termsOfService': 'شروط الخدمة',
      'privacyPolicy': 'سياسة الخصوصية',
      'resetPassword': 'إعادة تعيين كلمة المرور',
      'resetPasswordLead': 'أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور.',
      'sendResetLink': 'إرسال رابط إعادة التعيين',
      'backToLogin': 'العودة لتسجيل الدخول',
      'continueAsGuest': 'المتابعة كزائر',
      'exploreAsGuest': 'استكشاف كزائر',
      'guestSubtitle': 'استكشف النماذج المالية ومؤشرات السوق بدون تسجيل',
      'guestUser': 'مستخدم زائر',
      'guestMode': 'وضع الاستكشاف (زائر)',
      'guestNotice': 'تتصفح حالياً كزائر بدون حساب.',
      'guestBannerTitle': 'تتصفح كزائر',
      'guestBannerDesc': 'سجّل دخولك أو أنشئ حساباً مجانياً لحفظ ملفك ومزامنة دراساتك عبر أجهزتك.',
      'signInOrRegister': 'تسجيل الدخول / إنشاء حساب',
      'accountRequired': 'يتطلب تسجيل الدخول',
      'accountRequiredMessage': 'هذه الميزة تتطلب حساباً مجانياً. هل تود تسجيل الدخول أو إنشاء حساب الآن؟',
      'exitGuestMode': 'الخروج من وضع الزائر',
      'orDivider': 'أو',

      // Navigation
      'navDashboard': 'الرئيسية',
      'navProjects': 'المشاريع',
      'navMarket': 'المؤشرات',
      'navSettings': 'الإعدادات',

      // Dashboard
      'portfolioOverview': 'نظرة عامة على المحفظة العقارية',
      'activeProjects': 'الدراسات النشطة',
      'totalPipelineValue': 'إجمالي قيمة المحفظة',
      'averageRoi': 'متوسط العائد على الاستثمار',
      'marketTrend': 'مؤشرات السوق الإقليمية',
      'recentStudies': 'أحدث دراسات الجدوى',
      'viewAll': 'عرض الكل',
      'newStudy': '+ دراسة جديدة',
      'goDecision': 'مجدي',
      'noGoDecision': 'غير مجدي',
      'cautionDecision': 'تحذير',
      'liveMarketUpdate': 'بيانات السوق المباشرة',

      // Feasibility & Financial Metrics
      'projectDetails': 'تعريف المشروع',
      'projectName': 'اسم المشروع',
      'projectType': 'نوع الأصل العقاري',
      'location': 'المدينة / السوق',
      'landArea': 'مساحة الأرض',
      'far': 'معامل مسطحات البناء',
      'bua': 'إجمالي مساحة البناء',
      'gfa': 'المساحة الطابقية القابلة للتأجير',
      'landCost': 'تكلفة شراء الأرض',
      'constructionCostPerSqm': 'تكلفة البناء / م²',
      'softCostPct': 'المصاريف الاستشارية والإدارية (%)',
      'contingencyPct': 'احتياطي الطوارئ (%)',
      'expectedRevenuePerSqm': 'الإيراد المتوقع / م²',
      'developmentPeriodMonths': 'مدة التطوير (شهور)',
      'calculate': 'تنفيذ نموذج الجدوى',
      'verdict': 'نتيجة الجدوى',
      'verdictScore': 'مؤشر الجدوى والجاذبية',
      'totalDevelopmentCost': 'إجمالي تكلفة التطوير',
      'grossRevenue': 'إجمالي الإيرادات المتوقعة',
      'netProfit': 'صافي الربح المتوقع',
      'roi': 'العائد على الاستثمار',
      'irr': 'معدل العائد الداخلي',
      'equityMultiple': 'مضاعف حقوق الملكية',
      'profitMargin': 'هامش الربح على التكلفة',
      'breakeven': 'نقطة التعادل / م²',
      'costBreakdown': 'تحليل وتوزيع عناصر التكلفة',
      'cashFlowProjection': 'التدفقات النقدية ومراحل المشروع',
      'saveProject': 'حفظ في المشاريع',
      'exportPdf': 'تصدير ملخص الدراسة',
      'scenarioAnalysis': 'تحليل الحساسية والسيناريوهات',
      'baseCase': 'السيناريو الأساسي',
      'bullCase': 'السيناريو المتفائل (+10%)',
      'bearCase': 'السيناريو المتحفظ (-10%)',

      // Asset Types
      'residential': 'سكني',
      'commercial': 'تجاري / مكاتب',
      'mixedUse': 'متعدد الاستخدامات',
      'hospitality': 'فندقي وضيافة',
      'retail': 'تجزئة ومراكز تجارية',
      'industrial': 'صناعي ولوجستي',

      // Markets
      'riyadh': 'الرياض، السعودية',
      'jeddah': 'جدة، السعودية',
      'dubai': 'دبي، الإمارات',
      'abuDhabi': 'أبوظبي، الإمارات',
      'cairo': 'القاهرة، مصر',
      'doha': 'الدوحة، قطر',
      'kuwaitCity': 'مدينة الكويت، الكويت',

      // Settings
      'profile': 'الملف الشخصي والمنظمة',
      'appearance': 'المظهر',
      'darkMode': 'الوضع الداكن',
      'language': 'اللغة',
      'currency': 'العملة',
      'unit': 'وحدة قياس المساحة',
      'sqm': 'متر مربع (م²)',
      'sqft': 'قدم مربع',
      'about': 'عن منصة فاليوإيت',
      'version': 'الإصدار 1.0.0 - سحابة الشرق الأوسط',
      'signOut': 'تسجيل الخروج',
      'deleteAccount': 'حذف الحساب',

      // Project Wizard & Creation
      'createProjectTitle': 'إنشاء مشروع',
      'createProjectSubtitleStep1': 'تفاصيل المشروع الأساسية، بما في ذلك الاسم والموقع والنوع لتوفير نظرة شاملة عن نطاق المشروع وأهدافه.',
      'createProjectSubtitleStep2': 'النمذجة المالية، تقديرات التكاليف وسعر البيع والجدول الزمني لحساب الجدوى والعوائد بدقة.',
      'step1Title': 'المعلومات الأولية',
      'step2Title': 'النمذجة المالية',
      'developerName': 'اسم المطور',
      'developerNamePlaceholder': 'أدخل اسم المطور',
      'projectNamePlaceholder': 'أدخل اسم المشروع',
      'projectSectors': 'قطاعات المشروع',
      'strategyType': 'النوع',
      'selectType': 'اختر النوع',
      'selectCountry': 'يرجى اختيار خيار',
      'projectLocation': 'موقع المشروع',
      'locationMapPlaceholder': 'انقر لتحديد الموقع على الخريطة',
      'chooseOnMap': 'اختر علي الخريطه',
      'landAreaSqm': 'مساحة الأرض',
      'country': 'البلد',
      'citySubmarket': 'المدينة / الحي',
      'landPaymentStructure': 'هيكل دفع الأرض',
      'constructionSpecs': 'مواصفات البناء والمسطحات',
      'costAndPricing': 'تقديرات التكلفة وسعر البيع',
      'developmentTimeline': 'الجدول الزمني للتطوير',
      'previous': 'السابق',
      'next': 'التالي',
      'saveAndCreate': 'حفظ وإنشاء المشروع',

      // Alerts & Validation
      'fieldRequired': 'هذا الحقل مطلوب',
      'invalidEmail': 'يرجى إدخال بريد إلكتروني صحيح',
      'passwordLength': 'يجب ألا تقل كلمة المرور عن 6 خانات',
      'studySavedSuccess': 'تم إنشاء وحفظ المشروع بنجاح في مساحة العمل!',
      'linkSent': 'تم إرسال تعليمات إعادة التعيين إلى بريدك الإلكتروني.'
    }
  };

  static String get(String key, {String locale = 'en'}) {
    return localizedValues[locale]?[key] ?? localizedValues['en']?[key] ?? key;
  }
}
